# Generated by Django 5.1.7 on 2025-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSidebarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestText', models.CharField(max_length=300)),
                ('locaionText', models.CharField(max_length=300)),
                ('emailText', models.EmailField(max_length=254, verbose_name='example@gmail.com')),
                ('googleScholarLink', models.CharField(max_length=300)),
                ('linkedInLink', models.CharField(max_length=300)),
                ('twitterLink', models.CharField(max_length=300)),
                ('githubLink', models.CharField(max_length=300)),
                ('orcidLink', models.CharField(max_length=300)),
                ('researchGateLink', models.CharField(max_length=300)),
            ],
        ),
    ]
