# Generated by Django 5.1.7 on 2025-03-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_homesidebarinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolNameText', models.CharField(max_length=300)),
                ('degreeNameText', models.CharField(max_length=300)),
                ('departmentNameText', models.CharField(max_length=300)),
                ('certificateLink', models.CharField(max_length=300)),
                ('durationText', models.CharField(max_length=300)),
                ('gradeText', models.CharField(max_length=300)),
                ('transcriptLink', models.CharField(max_length=300)),
            ],
        ),
    ]
