# Generated by Django 5.1.7 on 2025-03-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_alter_educationitem_certificatelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationitem',
            name='transcriptLink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
