# Generated by Django 5.1.7 on 2025-05-22 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_educationitem_schoolwebsitelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_link', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
