# Generated by Django 5.1.7 on 2025-03-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_educationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationitem',
            name='certificateLink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='educationitem',
            name='departmentNameText',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='educationitem',
            name='gradeText',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
