# Generated by Django 5.1.7 on 2025-03-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_educationitem_transcriptlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationitem',
            name='schoolWebsiteLink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
