# Generated by Django 5.1.7 on 2025-07-19 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_jobexperienceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('acheivementLink', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
