# Generated by Django 5.1.7 on 2025-07-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_section_category_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
    ]
