# Generated by Django 5.1.7 on 2025-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_category_categories_rename_skill_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
