# Generated by Django 5.1.7 on 2025-07-21 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_skills_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperienceitem',
            name='company_logo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
