# Generated by Django 5.1.7 on 2025-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_jobexperienceitem_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperienceitem',
            name='company_logo',
            field=models.ImageField(upload_to='company_icons/'),
        ),
    ]
