# Generated by Django 5.1.7 on 2025-07-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_jobexperienceitem_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperienceitem',
            name='isVoluntary',
            field=models.BooleanField(default=False),
        ),
    ]
