# Generated by Django 5.1.7 on 2025-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_jobexperienceitem_isvoluntary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('tags', models.JSONField(default=list)),
            ],
        ),
    ]
