# Generated by Django 5.1.7 on 2025-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_projectsection_remove_project_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
