# Generated by Django 5.1.7 on 2025-07-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_projectsection_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('year', models.DateField()),
                ('name_url', models.URLField()),
                ('authors', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('publication_name', models.CharField(max_length=100)),
                ('publication_url', models.URLField()),
                ('pdf_url', models.URLField()),
                ('code', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/project_images/'),
        ),
    ]
