# Generated by Django 5.1.7 on 2025-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_publication_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
