# Generated by Django 5.1.7 on 2025-08-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_publication_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
