# Generated by Django 5.1.7 on 2025-08-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_project_youtube'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
