# Generated by Django 5.1.7 on 2025-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_rename_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='serial',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
