# Generated by Django 5.1.7 on 2025-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_projectsection_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='serial',
            field=models.IntegerField(),
        ),
    ]
