# Generated by Django 5.1.7 on 2025-08-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_projectsection_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
